### ISSUE TITLE
[BUG] Font issues

### ISSUE THREAD

**Issue by noClaps** [discuitnet/discuit#110] opened 2024-06-08 22:45 UTC
- [ ] [Font rendering incorrectly](https://discuit.net/DiscuitMeta/post/wxUGryY5)
- [x] [Word breaking when it should be in a single line](https://discuit.net/DiscuitMeta/post/MtAzayzg/17d71cd97fa169bbbb58ad1c)

I'll keep adding new comments as they come, but these should be extracted into their own issues and fixed.

**Comment by previnder** [comment] 2024-06-09 16:38
> - [ ] [Word breaking when it should be in a single line](https://discuit.net/DiscuitMeta/post/MtAzayzg/17d71cd97fa169bbbb58ad1c)

Fixed in f31b1d52.

**Comment by ttaylor-st** [comment] 2024-06-24 01:16
> [Font rendering incorrectly](https://discuit.net/DiscuitMeta/post/wxUGryY5)

I'm fairly certain this is caused by a [regression in WebKit](https://bugs.webkit.org/show_bug.cgi?id=247987) where it's not automatically setting the optical size. Should only affect Safari 16.0-16.4 on iOS + macOS

We could either:
- modify Inter, to "remove the named instances with a non-default `opsz`." [(source)](https://bugs.webkit.org/show_bug.cgi?id=247987#c4), 
- or explicitly state `opsz` in `font-variation-settings` for the affected versions

**Comment by ttaylor-st** [comment] 2024-06-25 22:45
Oh, looks like [someone already made an issue in the Inter repo](https://github.com/rsms/inter/issues/589) but it was closed as not planned

I'll just go ahead and make a PR to add the workaround

**Closed** 2024-06-30 19:25 UTC
Labels: bug
